server:
  port: 9082

spring:
  config:
    import: optional:configserver:http://localhost:9082/

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

#eureka:
#  instance:
#    prefer-ip-address: true

#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka