server:
  port: 9083

spring:
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:9083/

  datasource:
    url: jdbc:postgresql://localhost:5432/ratingService
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

